kind: StatefulSet
apiVersion: apps/v1
metadata:
  labels:
    app: edev-service-eureka-cluster
    project: edev-service-trade
  name: eureka
  namespace: default
spec:
  replicas: 3
  serviceName: eureka
  podManagementPolicy: "Parallel"
  selector:
    matchLabels:
      app: edev-service-eureka-cluster
  template:
    metadata:
      name: eureka
      labels:
        app: edev-service-eureka-cluster
        project: edev-service-trade
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - edev-service-eureka-cluster
                  - key: "project"
                    operator: In
                    values:
                      - edev-service-trade
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: edev-service-eureka-cluster
        image: repository:5000/edev-service-eureka:<VERSION>
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 500m
            memory: 1500Mi
          requests:
            cpu: 100m
            memory: 1000Mi
        args: [--spring.profiles.active=cluster]
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: SERVICE_HOST
          value: ${POD_NAME}.eureka
        - name: REGISTRY_URL
          value: "http://eureka-0.eureka:9001/eureka,http://eureka-1.eureka:9001/eureka,http://eureka-2.eureka:9001/eureka"
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: edev-service-eureka-cluster
    project: edev-service-trade
  name: eureka
  namespace: default
spec:
  ports:
  - name: http 
    port: 9001
  clusterIP: None
  selector:
    app: edev-service-eureka-cluster
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-eureka
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: eureka
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: edev-service-eureka-cluster
                port:
                  number: 9001
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: edev-service-eureka-cluster-pdb
  namespace: default
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: edev-service-eureka-cluster