spring:
  application:
    name: service-customer
  profiles:
    active: dev
  config:
    import: "optional:configserver:"
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis:
  mapperLocations: classpath*:mapper/*Mapper.xml
logging:
  level:
    com.edev.trade: INFO
    com.edev.support: INFO
    com.edev.trade.query.dao: DEBUG
    com.edev.support.dao: DEBUG
    com.edev.support.cache: DEBUG
    com.edev.trade.customer.event: DEBUG
---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://kubernetes:32306/edevCustomer?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: customer
    password: customer1234
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    database: 0
    host: kubernetes
    port: 31379
    password: redis1234
    pool:
      maxActive: 200
      maxWait: -1
      maxIdel: 10
      minIdel: 0
    timeout: 1000
  rabbitmq:
    host: kubernetes
    port: 31672
    username: admin
    password: rabbit1234
  cloud:
    stream:
      bindings:
        placeOrder:
          destination: placeOrder
          group: ${spring.application.name}
        returnGoods:
          destination: returnGoods
          group: ${spring.application.name}
  #    rocketmq:
  #      binder:
  #        name-server: kubernetes:30876
  #kafka:
  #  binder:
  #    zk-nodes: kubernetes:32181
  #  bootstrap-servers: kubernetes:30092
server:
  port: 9002
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka
---
spring:
  profiles: docker
  cloud:
    config:
      uri: ${GIT_URL}
      failFast: true
server:
  port: ${SERVICE_PORT:9002}