spring:
  application:
    name: service-inventory
  profiles:
    active: dev
  config:
    import: "optional:configserver:"
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis:
  mapperLocations: classpath*:mapper/*Mapper.xml
feign:
  hystrix:
    enabled: true
logging:
  level:
    com.edev.trade: INFO
    com.edev.support: INFO
    com.edev.trade.query.dao: DEBUG
    com.edev.support.dao: DEBUG
    com.edev.trade.inventory.event: DEBUG
---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://kubernetes:32306/edevInventory?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: inventory
    password: inventory1234
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    database: 0
    host: kubernetes
    port: 31379
    password: redis1234
    pool:
      maxActive: 200
      maxWait: -1
      maxIdel: 10
      minIdel: 0
    timeout: 1000
  rabbitmq:
    host: kubernetes
    port: 31672
    username: admin
    password: rabbit1234
  cloud:
    stream:
      bindings:
        placeOrder:
          destination: placeOrder
          group: ${spring.application.name}
        returnGoods:
          destination: returnGoods
          group: ${spring.application.name}
  #    rocketmq:
  #      binder:
  #        name-server: kubernetes:30876
  #kafka:
  #  binder:
  #    zk-nodes: kubernetes:32181
  #  bootstrap-servers: kubernetes:30092
server:
  port: 9004
ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 2000
  MaxAutoRetries: 0 # default 0
  MaxAutoRetriesNextServer: 2 # default 1
  OkToRetryOnAllOperations: true # default false
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka
---
spring:
  profiles: docker
  cloud:
    config:
      uri: ${GIT_URL}
      failFast: true
server:
  port: ${SERVICE_PORT:9004}