kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: edev-trade-product
  name: edev-trade-product
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edev-trade-product
  template:
    metadata:
      name: edev-trade-product
      labels:
        app: edev-trade-product
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - edev-trade-product
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: edev-trade-product
        image: repository:5000/edev-trade-product:<VERSION>
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 500m
            memory: 1500Mi
          requests:
            cpu: 100m
            memory: 1000Mi
        env:
          - name: GIT_URL
            value: "http://edev-service-config:9000"
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: edev-trade-product
  name: edev-trade-product
  namespace: default
spec:
  ports:
  - port: 9003 
    targetPort: 9003
  selector:
    app: edev-trade-product
