node {
    def parent = 'edev-service-trade'
    def app = 'edev-trade-parent'
    stage('拉取代码') {
        git "https://gitee.com/mooodo/${parent}.git"
    }
    stage('编译发布') {
        sh """
        cd ${app}
        mvn clean install
        """
    }
}