kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: edev-trade-gateway
  name: edev-trade-gateway 
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edev-trade-gateway
  template:
    metadata:
      name: edev-trade-gateway
      labels:
        app: edev-trade-gateway
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - edev-trade-gateway
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: edev-trade-gateway
        image: repository:5000/edev-trade-gateway:<VERSION>
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 500m
            memory: 1500Mi
          requests:
            cpu: 100m
            memory: 1000Mi
        env:
          - name: GIT_URL
            value: "http://edev-service-config:9000"
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: edev-trade-gateway
  name: edev-trade-gateway
  namespace: default
spec:
  ports:
  - port: 9009
    targetPort: 9009
  selector:
    app: edev-trade-gateway
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-edev-trade
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: trade
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: edev-trade-gateway
                port:
                  number: 9009