kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: edev-service-config
    project: edev-service-trade
  name: edev-service-config 
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edev-service-config
  template:
    metadata:
      name: edev-service-config
      labels:
        app: edev-service-config
        project: edev-service-trade
    spec:
      affinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - edev-service-config
                  - key: "project"
                    operator: In
                    values:
                      - edev-service-trade
      containers:
      - name: edev-service-config 
        image: repository:5000/edev-service-config:<VERSION>
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 500m
            memory: 1500Mi
          requests:
            cpu: 100m
            memory: 1000Mi
        args: ["--spring.profiles.active=docker"]
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: edev-service-config
    project: edev-service-trade
  name: edev-service-config
  namespace: default
spec:
  ports:
  - port: 9000 
    targetPort: 9000
  selector:
    app: edev-service-config
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-config
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: config
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: edev-service-config
                port:
                  number: 9000
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: edev-service-config-pdb
  namespace: default
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: edev-service-config