kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: edev-trade-product
    project: edev-service-trade
  name: edev-trade-product
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edev-trade-product
  template:
    metadata:
      name: edev-trade-product
      labels:
        app: edev-trade-product
        project: edev-service-trade
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 50
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: "app"
                      operator: In
                      values:
                        - edev-trade-product
                    - key: "project"
                      operator: In
                      values:
                        - edev-service-trade
                topologyKey: "kubernetes.io/hostname"
      containers:
      - name: edev-trade-product
        image: repository:5000/edev-trade-product
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 500m
            memory: 1500Mi
          requests:
            cpu: 100m
            memory: 1000Mi
        command: ["java", "-Djava.security.egd=file:/dev/./urandom", "-javaagent:/var/lib/skywalking/agent/skywalking-agent.jar", "-jar", "/app.jar","--spring.profiles.active=docker"]
        env:
          - name: GIT_URL
            value: "http://edev-service-config:9000"
          - name: SW_AGENT_NAME
            value: "service-product"
          - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
            value: "skywalking:11800"
        volumeMounts:
        - name: skywalking
          mountPath: /var/lib/skywalking
      initContainers:
      - name: init
        image: repository:5000/skywalking-java-agent
        command: ['sh','-c','cp -r /agent /var/lib/skywalking']
        volumeMounts:
        - name: skywalking
          mountPath: /var/lib/skywalking
      volumes:
      - name: skywalking
        emptyDir: {}
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: edev-trade-product
    project: edev-service-trade
  name: edev-trade-product
  namespace: default
spec:
  ports:
  - port: 9003
    targetPort: 9003
  selector:
    app: edev-trade-product
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: edev-trade-product-pdb
  namespace: default
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: edev-trade-product