eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 10 #default 90s
    lease-renewal-interval-in-seconds: 5 #default 30s
  client:
    service-url:
      defaultZone: http://eureka-0.eureka:9001/eureka/,http://eureka-1.eureka:9001/eureka/,http://eureka-2.eureka:9001/eureka/
  healthcheck:
    enabled: true
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    bus:
      trace:
        enabled: true
    loadbalancer:
      retry:
        enabled: true
  redis:
    database: 0
    host: redis
    port: 6379
    # cluster:
    #   nodes: redis-cluster-0.redis-cluster:6379,redis-cluster-1.redis-cluster:6379,redis-cluster-2.redis-cluster:6379
    password: redis1234
    pool:
      maxActive: 200
      maxWait: -1
      maxIdel: 10
      minIdel: 0
    timeout: 1000
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 2000
  MaxAutoRetries: 0 # default 0
  MaxAutoRetriesNextServer: 2 # default 1
  OkToRetryOnAllOperations: true # default false
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000
management:
  endpoints:
    web:
      exposure: 
        include: 'hystrix.stream'
