eureka:
  client:
    registry-fetch-interval-seconds: 5 #default 30s
spring:
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://service-customer
          predicates:
            - Path=/customer/**
          filters:
            - StripPrefix=1
        - id: product
          uri: lb://service-product
          predicates:
            - Path=/product/**
          filters:
            - StripPrefix=1
        - id: order
          uri: lb://service-order
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1
        - id: inventory
          uri: lb://service-inventory
          predicates:
            - Path=/inventory/**
          filters:
            - StripPrefix=1
        - id: else
          uri: https://www.baidu.com/
          predicates:
            - Path=/**
          filters:
            - StripPrefix=0
ribbon:
  connectTimeout: 2000
  readTimeout: 5000
  maxAutoRetries: 0
  maxAutoRetriesNextServer: 3
  okToRetryOnAllOperations: true