spring:
  datasource:
    url: jdbc:mysql://172.31.87.109:4000/edevOrder?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: trade
    password: trade1234
    type: com.alibaba.druid.pool.DruidDataSource