spring:
  datasource:
    url: jdbc:mysql://mysql-0.mysql:3306/edevInventory?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: inventory
    password: inventory1234